// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqccgeefnzfkptgnsrpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxY2NnZWVmbnpma3B0Z25zcnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjI3NzgsImV4cCI6MjA3MTkzODc3OH0.Vu0xW4931gHTrlr2e7QtOdp3yxFEEtfqt0VFXpZ_WDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});